library(WGCNA)
setwd("C:/Users/zeng/Desktop")
aa <- read.csv("abun1.csv",header = T,row.names = 1)
bb <- read.csv("abun2.csv",header = T,row.names = 1)
metaGeneCor.r <- cor(aa,bb,method="spearman")
write.csv(metaGeneCor.r,file="aa_bb.r.csv")
nn=nrow(aa)
metaGeneCor.p <- corPvalueStudent(metaGeneCor.r, nn)
write.csv(metaGeneCor.p,file = "aa_bb.p.csv")